/**:
  ros__parameters:
    cluster_max_size: 1000
    cluster_min_size: 46
    cluster_tol: 0.02
    plane_dist_thresh: 0.006
    plane_max_iter: 50
    ror_min_neighbors: 3
    ror_radius_search: 0.01
    voxel_leaf_size: 0.004
    x_filter_max: 0.16000000000000003
    x_filter_min: -0.12
    y_filter_max: 0.15000000000000002
    y_filter_min: -0.14
    z_filter_max: 0.5800000000000001
    z_filter_min: 0.30000000000000004
